# home/apps/nvim/default.nix
# Neovim via pkgs.wrapNeovim – plugins managed by Nix, Lua config lives in
# ~/.config/nvim/ (symlinked to ./lua/) and is loaded at runtime.
# Lua changes take effect immediately without a rebuild.
# Only plugin changes require nixos-rebuild.

{ pkgs, ... }:
let
  theme = import ../../colors/theme.nix;

  # Generate a colors.lua from the active Nix theme so Neovim can read them
  # at startup. No external colorscheme plugin needed.
  colorsLua = pkgs.writeText "colors.lua" ''
    -- Auto-generated by Nix – do not edit manually.
    -- To change the theme: edit home/colors/theme.nix and rebuild.
    return {
      -- ── Base ────────────────────────────────────────────────────────────────
      crust    = "#${theme.crust}",
      mantle   = "#${theme.mantle}",
      base     = "#${theme.base}",
      surface0 = "#${theme.surface0}",
      surface1 = "#${theme.surface1}",
      surface2 = "#${theme.surface2}",

      -- ── Text ────────────────────────────────────────────────────────────────
      overlay0 = "#${theme.overlay0}",
      overlay1 = "#${theme.overlay1}",
      overlay2 = "#${theme.overlay2}",
      subtext0 = "#${theme.subtext0}",
      subtext1 = "#${theme.subtext1}",
      text     = "#${theme.text}",

      -- ── Primary Accent ──────────────────────────────────────────────────────
      accent   = "#${theme.accent}",
      accent2  = "#${theme.accent2}",
      accent3  = "#${theme.accent3}",

      -- ── Secondary Accent ────────────────────────────────────────────────────
      accent_b  = "#${theme.accent_b}",
      accent_b2 = "#${theme.accent_b2}",

      -- ── Semantic ────────────────────────────────────────────────────────────
      error   = "#${theme.error}",
      error2  = "#${theme.error2}",
      warning = "#${theme.warning}",
      caution = "#${theme.caution}",
      success = "#${theme.success}",
      info    = "#${theme.info}",
      info2   = "#${theme.info2}",
      link    = "#${theme.link}",
      link2   = "#${theme.link2}",

      -- ── Syntax ──────────────────────────────────────────────────────────────
      syn_keyword     = "#${theme.syn_keyword}",
      syn_func        = "#${theme.syn_func}",
      syn_func_call   = "#${theme.syn_func_call}",
      syn_type        = "#${theme.syn_type}",
      syn_string      = "#${theme.syn_string}",
      syn_number      = "#${theme.syn_number}",
      syn_operator    = "#${theme.syn_operator}",
      syn_punctuation = "#${theme.syn_punctuation}",
      syn_comment     = "#${theme.syn_comment}",
      syn_constant    = "#${theme.syn_constant}",
      syn_attribute   = "#${theme.syn_attribute}",
      syn_namespace   = "#${theme.syn_namespace}",

      -- ── Markdown ────────────────────────────────────────────────────────────
      syn_md_h1          = "#${theme.syn_md_h1}",
      syn_md_h2          = "#${theme.syn_md_h2}",
      syn_md_h3          = "#${theme.syn_md_h3}",
      syn_md_h4          = "#${theme.syn_md_h4}",
      syn_md_code        = "#${theme.syn_md_code}",
      syn_md_code_bg     = "#${theme.syn_md_code_bg}",
      syn_md_quote       = "#${theme.syn_md_quote}",
      syn_md_list        = "#${theme.syn_md_list}",
      syn_md_bold        = "#${theme.syn_md_bold}",
      syn_md_italic      = "#${theme.syn_md_italic}",
      syn_md_link        = "#${theme.syn_md_link}",
      syn_md_url         = "#${theme.syn_md_url}",
      syn_md_hr          = "#${theme.syn_md_hr}",
      syn_md_checkbox_on = "#${theme.syn_md_checkbox_on}",
      syn_md_checkbox_off= "#${theme.syn_md_checkbox_off}",
    }
  '';

  neovim = pkgs.wrapNeovim pkgs.neovim-unwrapped {
    configure = {
      customRC = ''
        lua dofile(vim.fn.stdpath("config") .. "/init.lua")
      '';

      packages.all.start = with pkgs.vimPlugins; [
        # ── UI ────────────────────────────────────────────────────────────
        mini-nvim
        which-key-nvim
        nui-nvim

        # ── Editor ────────────────────────────────────────────────────────
        nvim-treesitter.withAllGrammars
        nvim-autopairs
        indent-blankline-nvim
        hardtime-nvim
        conform-nvim
        nvim-surround
        todo-comments-nvim

        # ── Markdown / Notes ──────────────────────────────────────────────
        render-markdown-nvim
        obsidian-nvim

        # ── Navigation ────────────────────────────────────────────────────
        flash-nvim
        harpoon2

        # ── File Manager ──────────────────────────────────────────────────
        oil-nvim

        # ── Telescope ─────────────────────────────────────────────────────
        plenary-nvim
        telescope-nvim
        telescope-fzf-native-nvim

        # ── Git ───────────────────────────────────────────────────────────
        gitsigns-nvim

        # ── LSP ───────────────────────────────────────────────────────────
        nvim-lspconfig

        # ── Completion ────────────────────────────────────────────────────
        blink-cmp
        luasnip

        # ── Diagnostics ───────────────────────────────────────────────────
        trouble-nvim
      ];
    };

    extraMakeWrapperArgs = "--prefix PATH : ${
      pkgs.lib.makeBinPath (
        with pkgs;
        [
          nixd
          pyright
          rust-analyzer
          lua-language-server
          taplo
          nixfmt
          black
          rustfmt
          stylua
          wl-clipboard
          typescript-language-server
          svelte-language-server
          prettier
          nodejs
        ]
      )
    }";
  };
in
{
  home.packages = [ neovim ];

  # Symlink the Lua config to ~/.config/nvim so Neovim finds it at runtime
  home.file.".config/nvim" = {
    source = ./lua;
    recursive = true;
  };

  # Inject the generated colors.lua into the config dir
  home.file.".config/nvim/colors.lua".source = colorsLua;
}
